# Generated by Django 5.1.3 on 2025-01-03 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('courses', models.ManyToManyField(related_name='students', to='admin_app.courses')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.admin')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usernew')),
            ],
        ),
    ]
