# Generated by Django 5.1.3 on 2025-02-01 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentanswers')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentcred')),
            ],
            options={
                'unique_together': {('username', 'exam')},
            },
        ),
    ]
