# Generated by Django 5.1.3 on 2025-01-05 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentCred',
        ),
    ]
