# Generated by Django 5.1.3 on 2025-02-03 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_examattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswers',
            name='username',
        ),
        migrations.RemoveField(
            model_name='studentmarks',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='studentmarks',
            name='username',
        ),
        migrations.DeleteModel(
            name='ExamAttempt',
        ),
        migrations.DeleteModel(
            name='StudentAnswers',
        ),
        migrations.DeleteModel(
            name='StudentMarks',
        ),
    ]
