# Generated by Django 5.1.3 on 2025-01-11 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0009_instituteclass_institute'),
        ('home', '0001_initial'),
        ('student', '0002_delete_studentcred'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.instituteclass')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.admin')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usernew')),
            ],
        ),
    ]
