# Generated by Django 5.1.3 on 2025-02-03 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_alter_admin_institute'),
        ('student', '0004_examattempt_studentanswers_studentmarks'),
        ('teacher', '0004_exams'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='examname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.exams'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentcred'),
        ),
        migrations.AddField(
            model_name='studentanswers',
            name='examname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.exams'),
        ),
        migrations.AddField(
            model_name='studentanswers',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentcred'),
        ),
        migrations.AddField(
            model_name='studentmarks',
            name='examname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.exams'),
        ),
        migrations.AddField(
            model_name='studentmarks',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.admin'),
        ),
        migrations.AddField(
            model_name='studentmarks',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentcred'),
        ),
        migrations.AlterUniqueTogether(
            name='examattempt',
            unique_together={('username', 'examname')},
        ),
    ]
