# Generated by Django 5.1.3 on 2025-01-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_studentcred_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcred',
            name='classes',
            field=models.CharField(max_length=50),
        ),
    ]
