# Generated by Django 5.1.3 on 2025-01-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_studentcred_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.TextField()),
            ],
        ),
    ]
