# Generated by Django 5.1.3 on 2025-01-22 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_studentmarks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentMarks',
        ),
    ]
