# Generated by Django 5.1.3 on 2025-01-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_studentmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcred',
            name='password',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
