# Generated by Django 5.1.3 on 2025-01-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_studentcred_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcred',
            name='email',
            field=models.EmailField(default=0, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
