# Generated by Django 5.1.3 on 2025-01-25 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_studentcred_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswers',
            name='username',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student.studentcred'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentmarks',
            name='username',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student.studentcred'),
            preserve_default=False,
        ),
    ]
