# Generated by Django 5.1.3 on 2025-01-03 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_scheduled', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('examname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.courses')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherCred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.courses')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.admin')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usernew')),
            ],
        ),
    ]
