# Generated by Django 5.1.3 on 2025-02-02 20:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='exams',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
