# Generated by Django 5.1.3 on 2025-01-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exams',
            name='created',
        ),
        migrations.RemoveField(
            model_name='teachercred',
            name='course',
        ),
        migrations.AlterField(
            model_name='exams',
            name='examname',
            field=models.CharField(max_length=32),
        ),
    ]
