# Generated by Django 5.1.3 on 2025-01-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_remove_exams_created_remove_teachercred_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exams',
            old_name='examname',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='exams',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='exams',
            name='time_start',
        ),
        migrations.AddField(
            model_name='exams',
            name='class_exam',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exams',
            name='questions',
            field=models.TextField(default='0'),
            preserve_default=False,
        ),
    ]
