# Generated by Django 5.1.3 on 2025-02-03 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_exams_end_time_exams_start_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exams',
        ),
    ]
