# Generated by Django 5.1.3 on 2025-01-13 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_rename_examname_exams_subject_remove_exams_time_end_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exams',
        ),
    ]
