# Generated by Django 5.1.3 on 2025-02-03 11:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_alter_admin_institute'),
        ('teacher', '0003_delete_exams'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examname', models.CharField(max_length=50)),
                ('classes', models.CharField(max_length=50)),
                ('courses', models.CharField(max_length=32)),
                ('date_scheduled', models.DateField()),
                ('start_time', models.TimeField(default=django.utils.timezone.now)),
                ('end_time', models.TimeField(default=django.utils.timezone.now)),
                ('questions', models.TextField()),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.admin')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('institute', 'examname'), name='unique_field1_field2')],
            },
        ),
    ]
