# Generated by Django 5.1.3 on 2025-01-13 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_institutecourses_institute_delete_institutecode'),
        ('teacher', '0004_delete_exams'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.CharField(max_length=50)),
                ('courses', models.CharField(max_length=32)),
                ('date_scheduled', models.DateField()),
                ('questions', models.TextField()),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.admin')),
            ],
        ),
    ]
