# Generated by Django 5.1.3 on 2025-01-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_exams'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachercred',
            name='courses',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teachercred',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
