# Generated by Django 5.1.3 on 2025-01-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_teachercred_courses_alter_teachercred_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachercred',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
