# Generated by Django 5.1.3 on 2025-01-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_teachercred_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachercred',
            name='password',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
