# Generated by Django 5.1.3 on 2025-01-24 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_usertype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
