# Generated by Django 5.1.3 on 2025-02-01 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.usernew'),
        ),
        migrations.AddField(
            model_name='instituteclass',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.admin'),
        ),
        migrations.AddField(
            model_name='institutecourses',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.admin'),
        ),
    ]
