# Generated by Django 5.1.3 on 2025-02-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='institute',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
