# Generated by Django 5.1.3 on 2025-01-25 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_initial'),
        ('home', '0002_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.usernew'),
        ),
    ]
