# Generated by Django 5.1.3 on 2025-01-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_alter_institutecode_institute'),
        ('student', '0002_delete_studentcred'),
        ('teacher', '0002_remove_exams_created_remove_teachercred_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteCred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.TextField()),
                ('courses', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
