# Generated by Django 5.1.3 on 2025-01-06 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_institutecred_delete_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutecred',
            name='institute',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='admin_app.admin'),
            preserve_default=False,
        ),
    ]
