# Generated by Django 5.1.3 on 2025-01-06 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_institutecred_institute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutecred',
            name='institute',
        ),
    ]
