# Generated by Django 5.1.3 on 2025-01-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_remove_institutecred_institute'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InstituteCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='InstituteCred',
        ),
    ]
