# Generated by Django 5.1.3 on 2025-01-11 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_instituteclass_institutecourses_delete_institutecred'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituteclass',
            name='institute',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='admin_app.admin'),
            preserve_default=False,
        ),
    ]
